apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: terraform-k3s-hello-world
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: demo-apps-hello-world-stripprefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /hello-world
        pathType: Prefix
        backend:
          service:
            name: hello-world
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hello-world-stripprefix
spec:
  stripPrefix:
    prefixes:
      - /hello-world
