apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cringe-meter-strip
  namespace: cringe-meter
spec:
  stripPrefix:
    prefixes:
      - /cringe-meter
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cringe-meter
  namespace: cringe-meter
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: cringe-meter-cringe-meter-strip@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /cringe-meter
        pathType: Prefix
        backend:
          service:
            name: cringe-meter
            port:
              number: 80
