apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: screaming-into-void-strip
spec:
  stripPrefix:
    prefixes:
      - /screaming-into-void
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: screaming-into-void
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: demo-apps-screaming-into-void-strip@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /screaming-into-void
        pathType: Prefix
        backend:
          service:
            name: screaming-into-void
            port:
              number: 80
