apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: nicolas-cage-strip
spec:
  stripPrefix:
    prefixes:
      - /nicolas-cage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nicolas-cage
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: demo-apps-nicolas-cage-strip@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /nicolas-cage
        pathType: Prefix
        backend:
          service:
            name: nicolas-cage
            port:
              number: 80
