apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cowsay-fortune
  namespace: demo-apps
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: demo-apps-cowsay-fortune-strip-prefix@kubernetescrd
spec:
  rules:
  - http:
      paths:
      - path: /cowsay-fortune
        pathType: Prefix
        backend:
          service:
            name: cowsay-fortune
            port:
              number: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cowsay-fortune-strip-prefix
  namespace: demo-apps
spec:
  stripPrefix:
    prefixes:
      - /cowsay-fortune
